ARG ROS_VERSION=jazzy

FROM arm64v8/ros:${ROS_VERSION}

SHELL ["/bin/bash", "-c"]

# Update and build the vizanti package
RUN apt-get update

# Need openssh-client for git to work properly, can be removed when rosbridge has binaries properly updated.
RUN apt-get install openssh-client -y
RUN apt-get install ros-$ROS_DISTRO-rmw-fastrtps-dynamic-cpp -y
RUN apt-get install ros-$ROS_DISTRO-rmw-cyclonedds-cpp -y

RUN mkdir -p /home/colcon_ws/src
COPY . /home/colcon_ws/src/vizanti/.

# Note: There are breaking changes in the rosbridge suite for ROS versions. We need to switch based on version.
RUN if [ "${ROS_DISTRO}" == "humble" ] ; then \
      cd /home/colcon_ws/src/ \
      && git clone -b humble https://github.com/RobotWebTools/rosbridge_suite.git ; \
    else \
      cd /home/colcon_ws/src/ \
      && git clone -b ros2 https://github.com/RobotWebTools/rosbridge_suite.git ; \
    fi

# Install the RWS implementation alternative to ROSbridge.
RUN cd /home/colcon_ws/src/ \
    && git clone -b $ROS_DISTRO https://github.com/v-kiniv/rws.git ;

RUN rosdep update

RUN apt-get update
RUN cd /home/colcon_ws && rosdep install -i --from-path src -y ;

RUN source /opt/ros/${ROS_DISTRO}/setup.bash && cd /home/colcon_ws && colcon build

# Launch the Vizanti with RWS or ROSBridge
CMD source /home/colcon_ws/install/setup.bash \
    && \
    if [ "${USE_RWS}" == "true" ] ; then \
      ros2 launch vizanti_server vizanti_rws.launch.py ; \
    else \
      ros2 launch vizanti_server vizanti_server.launch.py ; \
    fi
